[project]
name = "mail-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "openai-agents[viz]>=0.2.9",
    "pydantic>=2.11.7",
    "python-dotenv>=1.1.1",
]
